services:
  db.api:
    image: postgres:15.3
    restart: "no"
    container_name: todo_fastify_db
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=todo
      - POSTGRES_USER=postgres
    networks:
      - todo_network

  todo.api:
    container_name: todo
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:docker@todo_fastify_db:5432/todo?schema=public
      - SERVER_PORT=3333
    networks:
      - todo_network
    depends_on:
      - db.api
    command: "./scripts/start_server.sh"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3333/health-check || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  todo.web:
    image: nginx:alpine
    container_name: todo_fastify_web
    networks:
      - todo_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://todo.api:3333/health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - todo.api
    volumes:
      - ./nginx:/etc/nginx
    ports:
      - 8080:80

networks:
  todo_network:
    name: todo_network
    external: false
    attachable: true
    driver: bridge
